# -*- coding: utf-8 -*-
"""exchange_rates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7cABib2HZtsr7ov9fXemlGihZ-u3uGw
"""

import requests
import pandas as pd
import io
import matplotlib.pyplot as plt

# --- Common configuration ---
entrypoint = 'https://sdw-wsrest.ecb.europa.eu/service/'
resource = 'data'
parameters = {
    'startPeriod': '2000-01-01',
    'endPeriod': '2018-10-01'
}

# --- Get CHF/EUR data ---
flowRef = 'EXR'
key_chf_eur = 'D.CHF.EUR.SP00.A'  # CHF per EUR (spot)
url_chf_eur = f"{entrypoint}{resource}/{flowRef}/{key_chf_eur}"
response_chf_eur = requests.get(url_chf_eur, params=parameters, headers={'Accept': 'text/csv'})
df_chf_eur = pd.read_csv(io.StringIO(response_chf_eur.text))
ts_chf_eur = df_chf_eur.filter(['TIME_PERIOD', 'OBS_VALUE'], axis=1)
ts_chf_eur.rename(columns={'OBS_VALUE': 'CHF/EUR'}, inplace=True)

# --- Get USD/EUR data ---
key_usd_eur = 'D.USD.EUR.SP00.A'  # USD per EUR (spot)
url_usd_eur = f"{entrypoint}{resource}/{flowRef}/{key_usd_eur}"
response_usd_eur = requests.get(url_usd_eur, params=parameters, headers={'Accept': 'text/csv'})
df_usd_eur = pd.read_csv(io.StringIO(response_usd_eur.text))
ts_usd_eur = df_usd_eur.filter(['TIME_PERIOD', 'OBS_VALUE'], axis=1)
ts_usd_eur.rename(columns={'OBS_VALUE': 'USD/EUR'}, inplace=True)

# --- Convert 'TIME_PERIOD' to datetime and set as index ---
ts_chf_eur['TIME_PERIOD'] = pd.to_datetime(ts_chf_eur['TIME_PERIOD'])
ts_usd_eur['TIME_PERIOD'] = pd.to_datetime(ts_usd_eur['TIME_PERIOD'])
ts_chf_eur.set_index('TIME_PERIOD', inplace=True)
ts_usd_eur.set_index('TIME_PERIOD', inplace=True)

# --- Merge the two series on their index ---
combined_ts = ts_chf_eur.join(ts_usd_eur, how='inner')

# --- Plotting ---
combined_ts.plot(title='CHF/EUR and USD/EUR Exchange Rates (2000–2018)', figsize=(12, 6))
plt.ylabel('Exchange Rate')
plt.grid(True)
plt.show()